import {
  AlAlert as Alert,
  AlBadge as Badge,
  AlButton as Button,
  AlCard as Card,
  AlCheckbox as Checkbox,
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
  ContextMenu,
  ContextMenuCheckboxItem,
  ContextMenuContent,
  ContextMenuGroup,
  ContextMenuItem,
  ContextMenuLabel,
  ContextMenuRadioGroup,
  ContextMenuRadioItem,
  ContextMenuSeparator,
  ContextMenuShortcut,
  ContextMenuSub,
  ContextMenuSubContent,
  ContextMenuSubTrigger,
  ContextMenuTrigger,
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogOverlay,
  DialogScrollContent,
  DialogTitle,
  DialogTrigger,
  AlDropdownMenu as DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenu as DropdownMenuRoot,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger,
  AlEmptyState as EmptyState,
  AlIconButton as IconButton,
  AlInput as Input,
  AlKeyValueList as KeyValueList,
  AlLabel as Label,
  AlPanel as Panel,
  AlPanelHeader as PanelHeader,
  ScrollArea,
  ScrollBar,
  AlSearchBar as SearchField,
  AlSection as Section,
  AlSectionHeader as SectionHeader,
  AlSelect as Select,
  AlSelectableItem as SelectableItem,
  AlSeparator as Separator,
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarInset,
  SidebarMenu,
  SidebarMenuBadge,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarProvider,
  SidebarRail,
  AlSidebarSection as SidebarSection,
  AlStatBlock as StatBlock,
  AlSwitch as Switch,
  AlTabs as Tabs,
  AlTextarea as Textarea,
} from '@activelane/shadcn'
import type { Component } from 'vue'

function defineComponentRegistry<const T extends Record<string, Component>>(
  registry: T,
): { readonly [K in keyof T]: Component } {
  return registry
}

export const workbenchComponentRegistry = defineComponentRegistry({
  Alert,
  Badge,
  Button,
  Card,
  Checkbox,
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
  ContextMenu,
  ContextMenuCheckboxItem,
  ContextMenuContent,
  ContextMenuGroup,
  ContextMenuItem,
  ContextMenuLabel,
  ContextMenuRadioGroup,
  ContextMenuRadioItem,
  ContextMenuSeparator,
  ContextMenuShortcut,
  ContextMenuSub,
  ContextMenuSubContent,
  ContextMenuSubTrigger,
  ContextMenuTrigger,
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogOverlay,
  DialogScrollContent,
  DialogTitle,
  DialogTrigger,
  DropdownMenu,
  DropdownMenuRoot,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger,
  EmptyState,
  IconButton,
  Input,
  KeyValueList,
  Label,
  Panel,
  PanelHeader,
  ScrollArea,
  ScrollBar,
  SearchField,
  Section,
  SectionHeader,
  Select,
  SelectableItem,
  Separator,
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarInset,
  SidebarMenu,
  SidebarMenuBadge,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarProvider,
  SidebarRail,
  SidebarSection,
  StatBlock,
  Switch,
  Tabs,
  Textarea,
})
