// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(1783146252);
}

export function Details(registryID: string, extensionID: string): $CancellablePromise<$models.SearchResponse> {
    return $Call.ByID(548962942, registryID, extensionID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Disable(extensionID: string): $CancellablePromise<$models.ExtensionOperationResponse> {
    return $Call.ByID(1711978116, extensionID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Enable(extensionID: string): $CancellablePromise<$models.ExtensionOperationResponse> {
    return $Call.ByID(3236311127, extensionID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Install(registryID: string, extensionID: string, version: string): $CancellablePromise<$models.ExtensionOperationResponse> {
    return $Call.ByID(196302027, registryID, extensionID, version).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Installed(): $CancellablePromise<$models.InstalledResponse> {
    return $Call.ByID(1682183818).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Registries(): $CancellablePromise<$models.RegistryStatusResponse> {
    return $Call.ByID(3943143959).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Search(query: string): $CancellablePromise<$models.SearchResponse> {
    return $Call.ByID(1082037956, query).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Uninstall(extensionID: string): $CancellablePromise<$models.ExtensionOperationResponse> {
    return $Call.ByID(196426714, extensionID).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SearchResponse.createFrom;
const $$createType1 = $models.ExtensionOperationResponse.createFrom;
const $$createType2 = $models.InstalledResponse.createFrom;
const $$createType3 = $models.RegistryStatusResponse.createFrom;
