// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DesktopError {
    "code": string;
    "message": string;
    "detail"?: string;

    /** Creates a new DesktopError instance. */
    constructor($$source: Partial<DesktopError> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopError instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopError($$parsedSource as Partial<DesktopError>);
    }
}

export class ExtensionOperationResponse {
    "record"?: InstalledExtension | null;
    "restartRequired": boolean;
    "error"?: DesktopError | null;

    /** Creates a new ExtensionOperationResponse instance. */
    constructor($$source: Partial<ExtensionOperationResponse> = {}) {
        if (!("restartRequired" in $$source)) {
            this["restartRequired"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtensionOperationResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ExtensionOperationResponse {
        const $$createField0_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("record" in $$parsedSource) {
            $$parsedSource["record"] = $$createField0_0($$parsedSource["record"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField2_0($$parsedSource["error"]);
        }
        return new ExtensionOperationResponse($$parsedSource as Partial<ExtensionOperationResponse>);
    }
}

export class FileHandle {
    "name": string;
    "path"?: string;
    "contents"?: string;

    /** Creates a new FileHandle instance. */
    constructor($$source: Partial<FileHandle> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileHandle instance from a string or object.
     */
    static createFrom($$source: any = {}): FileHandle {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileHandle($$parsedSource as Partial<FileHandle>);
    }
}

export class FileSystemEntry {
    "name": string;
    "path": string;
    "uri": string;
    "type": string;
    "size"?: number;
    "modifiedAt"?: string;
    "hidden"?: boolean;

    /** Creates a new FileSystemEntry instance. */
    constructor($$source: Partial<FileSystemEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileSystemEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FileSystemEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileSystemEntry($$parsedSource as Partial<FileSystemEntry>);
    }
}

export class InstalledExtension {
    "id": string;
    "extensionId": string;
    "displayName": string;
    "version": string;
    "enabled": boolean;
    "state": string;
    "installSource": string;
    "installedAt": string;
    "updatedAt": string;
    "manifest": { [_ in string]?: any };
    "registryId": string;
    "registrySource": string;
    "manifestDigest": string;
    "packageDigest": string;
    "installPath": string;
    "integrityState": string;
    "restartRequired": boolean;

    /** Creates a new InstalledExtension instance. */
    constructor($$source: Partial<InstalledExtension> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("extensionId" in $$source)) {
            this["extensionId"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("installSource" in $$source)) {
            this["installSource"] = "";
        }
        if (!("installedAt" in $$source)) {
            this["installedAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("manifest" in $$source)) {
            this["manifest"] = {};
        }
        if (!("registryId" in $$source)) {
            this["registryId"] = "";
        }
        if (!("registrySource" in $$source)) {
            this["registrySource"] = "";
        }
        if (!("manifestDigest" in $$source)) {
            this["manifestDigest"] = "";
        }
        if (!("packageDigest" in $$source)) {
            this["packageDigest"] = "";
        }
        if (!("installPath" in $$source)) {
            this["installPath"] = "";
        }
        if (!("integrityState" in $$source)) {
            this["integrityState"] = "";
        }
        if (!("restartRequired" in $$source)) {
            this["restartRequired"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstalledExtension instance from a string or object.
     */
    static createFrom($$source: any = {}): InstalledExtension {
        const $$createField9_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("manifest" in $$parsedSource) {
            $$parsedSource["manifest"] = $$createField9_0($$parsedSource["manifest"]);
        }
        return new InstalledExtension($$parsedSource as Partial<InstalledExtension>);
    }
}

export class InstalledResponse {
    "items": InstalledExtension[];
    "error"?: DesktopError | null;

    /** Creates a new InstalledResponse instance. */
    constructor($$source: Partial<InstalledResponse> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstalledResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): InstalledResponse {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new InstalledResponse($$parsedSource as Partial<InstalledResponse>);
    }
}

export class NetworkRequest {
    "method": string;
    "url": string;
    "headers": { [_ in string]?: string };
    "body": string;

    /** Creates a new NetworkRequest instance. */
    constructor($$source: Partial<NetworkRequest> = {}) {
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("headers" in $$source)) {
            this["headers"] = {};
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): NetworkRequest {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField2_0($$parsedSource["headers"]);
        }
        return new NetworkRequest($$parsedSource as Partial<NetworkRequest>);
    }
}

export class NetworkResponse {
    "status": number;
    "statusText": string;
    "durationMs": number;
    "sizeBytes": number;
    "headers": { [_ in string]?: string[] };
    "body": string;
    "error"?: DesktopError | null;

    /** Creates a new NetworkResponse instance. */
    constructor($$source: Partial<NetworkResponse> = {}) {
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("statusText" in $$source)) {
            this["statusText"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("headers" in $$source)) {
            this["headers"] = {};
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): NetworkResponse {
        const $$createField4_0 = $$createType8;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField4_0($$parsedSource["headers"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField6_0($$parsedSource["error"]);
        }
        return new NetworkResponse($$parsedSource as Partial<NetworkResponse>);
    }
}

export class RegistryFailure {
    "registryId": string;
    "registryDisplayName": string;
    "error": DesktopError;

    /** Creates a new RegistryFailure instance. */
    constructor($$source: Partial<RegistryFailure> = {}) {
        if (!("registryId" in $$source)) {
            this["registryId"] = "";
        }
        if (!("registryDisplayName" in $$source)) {
            this["registryDisplayName"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = (new DesktopError());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegistryFailure instance from a string or object.
     */
    static createFrom($$source: any = {}): RegistryFailure {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField2_0($$parsedSource["error"]);
        }
        return new RegistryFailure($$parsedSource as Partial<RegistryFailure>);
    }
}

export class RegistryStatus {
    "id": string;
    "displayName": string;
    "type": string;
    "source": string;
    "enabled": boolean;
    "priority": number;
    "scopes": string[];
    "state": string;
    "capabilities"?: { [_ in string]?: boolean };
    "error"?: DesktopError | null;

    /** Creates a new RegistryStatus instance. */
    constructor($$source: Partial<RegistryStatus> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("scopes" in $$source)) {
            this["scopes"] = [];
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegistryStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): RegistryStatus {
        const $$createField6_0 = $$createType7;
        const $$createField8_0 = $$createType9;
        const $$createField9_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scopes" in $$parsedSource) {
            $$parsedSource["scopes"] = $$createField6_0($$parsedSource["scopes"]);
        }
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField8_0($$parsedSource["capabilities"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField9_0($$parsedSource["error"]);
        }
        return new RegistryStatus($$parsedSource as Partial<RegistryStatus>);
    }
}

export class RegistryStatusResponse {
    "registries": RegistryStatus[];
    "mode": string;
    "publicRegistryEnabled": boolean;
    "error"?: DesktopError | null;

    /** Creates a new RegistryStatusResponse instance. */
    constructor($$source: Partial<RegistryStatusResponse> = {}) {
        if (!("registries" in $$source)) {
            this["registries"] = [];
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("publicRegistryEnabled" in $$source)) {
            this["publicRegistryEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegistryStatusResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): RegistryStatusResponse {
        const $$createField0_0 = $$createType11;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("registries" in $$parsedSource) {
            $$parsedSource["registries"] = $$createField0_0($$parsedSource["registries"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField3_0($$parsedSource["error"]);
        }
        return new RegistryStatusResponse($$parsedSource as Partial<RegistryStatusResponse>);
    }
}

export class SearchExtension {
    "registryId": string;
    "registryDisplayName": string;
    "id": string;
    "namespace": string;
    "name": string;
    "displayName": string;
    "description": string;
    "version": string;
    "versionStatus": string;
    "manifest": { [_ in string]?: any };
    "manifestDigest": string;
    "packageDigest": string;
    "publishedAt": string;
    "compatible": boolean;
    "compatibilityReason"?: string;

    /** Creates a new SearchExtension instance. */
    constructor($$source: Partial<SearchExtension> = {}) {
        if (!("registryId" in $$source)) {
            this["registryId"] = "";
        }
        if (!("registryDisplayName" in $$source)) {
            this["registryDisplayName"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("versionStatus" in $$source)) {
            this["versionStatus"] = "";
        }
        if (!("manifest" in $$source)) {
            this["manifest"] = {};
        }
        if (!("manifestDigest" in $$source)) {
            this["manifestDigest"] = "";
        }
        if (!("packageDigest" in $$source)) {
            this["packageDigest"] = "";
        }
        if (!("publishedAt" in $$source)) {
            this["publishedAt"] = "";
        }
        if (!("compatible" in $$source)) {
            this["compatible"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchExtension instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchExtension {
        const $$createField9_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("manifest" in $$parsedSource) {
            $$parsedSource["manifest"] = $$createField9_0($$parsedSource["manifest"]);
        }
        return new SearchExtension($$parsedSource as Partial<SearchExtension>);
    }
}

export class SearchResponse {
    "items": SearchExtension[];
    "failures": RegistryFailure[];
    "mode": string;
    "publicRegistryEnabled": boolean;
    "error"?: DesktopError | null;

    /** Creates a new SearchResponse instance. */
    constructor($$source: Partial<SearchResponse> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("failures" in $$source)) {
            this["failures"] = [];
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("publicRegistryEnabled" in $$source)) {
            this["publicRegistryEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResponse {
        const $$createField0_0 = $$createType13;
        const $$createField1_0 = $$createType15;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        if ("failures" in $$parsedSource) {
            $$parsedSource["failures"] = $$createField1_0($$parsedSource["failures"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        return new SearchResponse($$parsedSource as Partial<SearchResponse>);
    }
}

// Private type creation functions
const $$createType0 = InstalledExtension.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = DesktopError.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Array($$createType0);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = $Create.Map($Create.Any, $$createType7);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = RegistryStatus.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = SearchExtension.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = RegistryFailure.createFrom;
const $$createType15 = $Create.Array($$createType14);
