// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkspaceService owns native filesystem operations exposed to the workbench.
 * Dialog and window lifecycle APIs remain provided by the Wails runtime.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(672848412);
}

export function ReadDirectory(path: string): $CancellablePromise<$models.FileSystemEntry[]> {
    return $Call.ByID(1419904071, path).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ReadFile(path: string): $CancellablePromise<$models.FileHandle> {
    return $Call.ByID(2517090602, path).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Root(): $CancellablePromise<string> {
    return $Call.ByID(481862592);
}

export function SetRoot(path: string): $CancellablePromise<void> {
    return $Call.ByID(3834232000, path);
}

export function WriteFile(file: $models.FileHandle): $CancellablePromise<$models.FileHandle> {
    return $Call.ByID(4065064521, file).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FileSystemEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.FileHandle.createFrom;
