import type { WorkbenchSettingDefinition } from './types'

export const builtinWorkbenchSettings: WorkbenchSettingDefinition[] = [
  {
    id: 'workbench.layout.activityRail.expanded',
    label: 'Expanded Activity Rail',
    description: 'Shows labels beside activities and browser tabs in the activity rail.',
    category: 'Activity Bar',
    subcategory: 'Layout',
    type: 'boolean',
    defaultValue: false,
    tags: ['rail', 'navigation', 'tabs', 'compact'],
    integration: { status: 'wired' },
  },
  {
    id: 'files.autoSave',
    label: 'Auto Save',
    description: 'Automatically saves writable file editor tabs after edits.',
    category: 'Files',
    type: 'boolean',
    defaultValue: false,
    tags: ['files', 'save'],
    integration: { status: 'wired' },
  },
  // {
  //   id: 'workbench.appearance.theme',
  //   label: 'Color Theme',
  //   description: 'Controls the active Workbench color theme.',
  //   category: 'Appearance',
  //   subcategory: 'Theme',
  //   type: 'enum',
  //   defaultValue: 'system',
  //   options: [
  //     { label: 'System', value: 'system' },
  //     { label: 'Light', value: 'light' },
  //     { label: 'Dark', value: 'dark' },
  //     { label: 'High Contrast', value: 'high-contrast' },
  //     { label: 'VSCode Dark', value: 'vscode-dark' },
  //   ],
  //   tags: ['theme', 'color', 'dark', 'light'],
  // },
  // {
  //   id: 'workbench.appearance.density',
  //   label: 'Workbench Density',
  //   description: 'Adjusts spacing for the main Workbench chrome.',
  //   category: 'Appearance',
  //   type: 'enum',
  //   defaultValue: 'compact',
  //   options: [
  //     { label: 'Compact', value: 'compact' },
  //     { label: 'Comfortable', value: 'comfortable' },
  //   ],
  //   tags: ['spacing', 'compact', 'comfortable'],
  // },
  // {
  //   id: 'workbench.appearance.fontSize',
  //   label: 'Workbench Font Size',
  //   description: 'Base font size used by Workbench surfaces.',
  //   category: 'Appearance',
  //   type: 'number',
  //   defaultValue: 13,
  //   render: { min: 11, max: 18, step: 1 },
  //   tags: ['font', 'text', 'zoom'],
  // },
  // {
  //   id: 'workbench.appearance.reducedMotion',
  //   label: 'Reduced Motion',
  //   description: 'Reduces Workbench transition and animation intensity.',
  //   category: 'Appearance',
  //   type: 'boolean',
  //   defaultValue: false,
  //   tags: ['motion', 'animation', 'accessibility'],
  // },
  // {
  //   id: 'workbench.layout.sidebar.position',
  //   label: 'Sidebar Position',
  //   description:
  //     'Places the primary sidebar on the left or right. Right side is reserved until mirrored layout is enabled.',
  //   category: 'Sidebar',
  //   subcategory: 'Layout',
  //   type: 'enum',
  //   defaultValue: 'left',
  //   options: [
  //     { label: 'Left', value: 'left' },
  //     { label: 'Right', value: 'right' },
  //   ],
  //   requiresReload: true,
  //   integration: {
  //     status: 'reserved',
  //     reason:
  //       'The shell stores the preference now; mirrored sidebar layout will read it when right-side chrome is implemented.',
  //   },
  // },
  // {
  //   id: 'workbench.layout.sidebar.collapsed',
  //   label: 'Sidebar Collapsed',
  //   description: 'Controls whether the primary sidebar starts collapsed.',
  //   category: 'Sidebar',
  //   type: 'boolean',
  //   defaultValue: false,
  // },
  // {
  //   id: 'workbench.layout.sidebar.width',
  //   label: 'Sidebar Width',
  //   description: 'Width of the primary sidebar in pixels.',
  //   category: 'Sidebar',
  //   type: 'number',
  //   defaultValue: 320,
  //   render: { min: 220, max: 520, step: 10 },
  // },
  // {
  //   id: 'workbench.layout.activityRail.visible',
  //   label: 'Activity Bar Visible',
  //   description: 'Shows the left activity rail.',
  //   category: 'Activity Bar',
  //   type: 'boolean',
  //   defaultValue: true,
  //   tags: ['rail', 'navigation'],
  // },
  // {
  //   id: 'workbench.layout.activityRail.location',
  //   label: 'Activity Bar Location',
  //   description: 'Stores the preferred activity bar location.',
  //   category: 'Activity Bar',
  //   type: 'enum',
  //   defaultValue: 'left',
  //   options: [
  //     { label: 'Left', value: 'left' },
  //     { label: 'Right', value: 'right' },
  //     { label: 'Top', value: 'top' },
  //   ],
  // },
  // {
  //   id: 'workbench.layout.commandBar.visible',
  //   label: 'Command Bar Visible',
  //   description: 'Shows the top command and search toolbar.',
  //   category: 'Commands',
  //   type: 'boolean',
  //   defaultValue: true,
  // },
  // {
  //   id: 'workbench.layout.commandBar.location',
  //   label: 'Command Bar Location',
  //   description: 'Stores where the command bar should be hosted.',
  //   category: 'Commands',
  //   type: 'enum',
  //   defaultValue: 'workbench-top',
  //   options: [
  //     { label: 'Workbench Top', value: 'workbench-top' },
  //     { label: 'Title Bar', value: 'titlebar' },
  //   ],
  // },
  // {
  //   id: 'workbench.layout.tabs.visible',
  //   label: 'Tabs Visible',
  //   description: 'Shows editor tabs in tab groups.',
  //   category: 'Tabs',
  //   type: 'boolean',
  //   defaultValue: true,
  // },
  // {
  //   id: 'workbench.layout.tabs.compact',
  //   label: 'Compact Tabs',
  //   description: 'Uses a tighter tab strip.',
  //   category: 'Tabs',
  //   type: 'boolean',
  //   defaultValue: true,
  // },
  // {
  //   id: 'workbench.layout.panes.resizeMode',
  //   label: 'Pane Resize Mode',
  //   description: 'Controls how pane drag handles update adjacent surfaces.',
  //   category: 'Panes',
  //   type: 'enum',
  //   defaultValue: 'live',
  //   options: [
  //     { label: 'Live', value: 'live' },
  //     { label: 'Deferred', value: 'deferred' },
  //   ],
  // },
  // {
  //   id: 'workbench.layout.inspector.collapsed',
  //   label: 'Inspector Collapsed',
  //   description: 'Controls whether the inspector pane is collapsed.',
  //   category: 'Panes',
  //   type: 'boolean',
  //   defaultValue: false,
  // },
  // {
  //   id: 'workbench.layout.bottomPanel.open',
  //   label: 'Bottom Panel Open',
  //   description: 'Controls whether the bottom panel is open.',
  //   category: 'Panes',
  //   type: 'boolean',
  //   defaultValue: false,
  // },
  // {
  //   id: 'workbench.editor.defaultMode',
  //   label: 'Default Editor Mode',
  //   description: 'Default mode for editor-backed surfaces.',
  //   category: 'Editor',
  //   type: 'enum',
  //   defaultValue: 'rich-text',
  //   options: [
  //     { label: 'Rich Text', value: 'rich-text' },
  //     { label: 'Markdown', value: 'markdown' },
  //     { label: 'Source', value: 'source' },
  //   ],
  //   integration: {
  //     status: 'integration-point',
  //     reason:
  //       'Editor-capable extensions read this setting from runtime.settings when choosing their initial editing mode.',
  //   },
  // },
  // {
  //   id: 'workbench.editor.previewMode',
  //   label: 'Preview Mode',
  //   description: 'Opens eligible tabs as preview tabs until pinned or edited.',
  //   category: 'Editor',
  //   type: 'boolean',
  //   defaultValue: true,
  // },
  // {
  //   id: 'workbench.editor.wordWrap',
  //   label: 'Word Wrap',
  //   description: 'Wraps long lines in code-like editors when supported.',
  //   category: 'Editor',
  //   type: 'enum',
  //   defaultValue: 'on',
  //   options: [
  //     { label: 'Off', value: 'off' },
  //     { label: 'On', value: 'on' },
  //     { label: 'Bounded', value: 'bounded' },
  //   ],
  //   integration: {
  //     status: 'integration-point',
  //     reason:
  //       'Code and markdown renderers can use this setting through runtime.settings; the shell does not own editor text layout.',
  //   },
  // },
  // {
  //   id: 'workbench.editor.minimap',
  //   label: 'Minimap',
  //   description: 'Shows editor minimaps where the renderer supports them.',
  //   category: 'Editor',
  //   type: 'boolean',
  //   defaultValue: false,
  //   integration: {
  //     status: 'integration-point',
  //     reason:
  //       'Editor renderers can use this setting through runtime.settings when minimap support is available.',
  //   },
  // },
  // {
  //   id: 'workbench.extensions.autoUpdate',
  //   label: 'Auto Update Extensions',
  //   description: 'Automatically applies available extension updates.',
  //   category: 'Extensions',
  //   type: 'boolean',
  //   defaultValue: true,
  //   integration: {
  //     status: 'integration-point',
  //     reason: 'Marketplace providers can use this preference when update discovery is connected.',
  //   },
  // },
  // {
  //   id: 'workbench.extensions.allowExperimental',
  //   label: 'Allow Experimental Extensions',
  //   description: 'Allows extensions marked experimental to be enabled.',
  //   category: 'Extensions',
  //   type: 'boolean',
  //   defaultValue: false,
  // },
  // {
  //   id: 'workbench.commands.showRecent',
  //   label: 'Show Recent Commands',
  //   description: 'Shows recent commands in command surfaces when history is available.',
  //   category: 'Commands',
  //   type: 'boolean',
  //   defaultValue: true,
  //   integration: {
  //     status: 'reserved',
  //     reason:
  //       'Command history is not persisted yet; the preference is reserved for the command service history provider.',
  //   },
  // },
  // {
  //   id: 'workbench.keybindings.profile',
  //   label: 'Keyboard Profile',
  //   description: 'Selects the active keybinding profile.',
  //   category: 'Keyboard Shortcuts',
  //   type: 'enum',
  //   defaultValue: 'default',
  //   options: [
  //     { label: 'Default', value: 'default' },
  //     { label: 'VS Code', value: 'vscode' },
  //     { label: 'Minimal', value: 'minimal' },
  //   ],
  //   integration: {
  //     status: 'integration-point',
  //     reason:
  //       'The keybinding editor stores command overrides today; alternate full profiles can be resolved by future keybinding providers.',
  //   },
  // },
  // {
  //   id: 'workbench.notifications.enabled',
  //   label: 'Notifications Enabled',
  //   description: 'Allows Workbench and extension notifications.',
  //   category: 'Notifications',
  //   type: 'boolean',
  //   defaultValue: true,
  // },
  // {
  //   id: 'workbench.notifications.position',
  //   label: 'Notification Position',
  //   description: 'Preferred notification viewport position.',
  //   category: 'Notifications',
  //   type: 'enum',
  //   defaultValue: 'bottom-right',
  //   options: [
  //     { label: 'Bottom Right', value: 'bottom-right' },
  //     { label: 'Bottom Left', value: 'bottom-left' },
  //     { label: 'Top Right', value: 'top-right' },
  //     { label: 'Top Left', value: 'top-left' },
  //   ],
  //   integration: {
  //     status: 'integration-point',
  //     reason:
  //       'The shell exposes this value as runtime preference metadata; host toast renderers can use it for placement.',
  //   },
  // },
  // {
  //   id: 'workbench.privacy.telemetry',
  //   label: 'Telemetry',
  //   description: 'Allows privacy-preserving product telemetry.',
  //   category: 'Privacy',
  //   type: 'boolean',
  //   defaultValue: false,
  //   integration: {
  //     status: 'integration-point',
  //     reason:
  //       'Host telemetry providers should read this setting before recording optional product events.',
  //   },
  // },
  // {
  //   id: 'workbench.performance.lazyLoadExtensions',
  //   label: 'Lazy Load Extensions',
  //   description: 'Defers extension activation until a matching activation event.',
  //   category: 'Extensions',
  //   type: 'boolean',
  //   defaultValue: true,
  //   integration: {
  //     status: 'reserved',
  //     reason:
  //       'Startup activation is currently manifest-driven; this preference is reserved for the extension activation scheduler.',
  //   },
  // },
  // {
  //   id: 'workbench.developer.showDiagnostics',
  //   label: 'Show Diagnostics',
  //   description: 'Shows runtime diagnostics and extension surface errors.',
  //   category: 'Developer',
  //   type: 'boolean',
  //   defaultValue: false,
  // },
  // {
  //   id: 'workbench.developer.extensionHostDebug',
  //   label: 'Extension Host Debug',
  //   description: 'Enables extra extension host debug state.',
  //   category: 'Developer',
  //   type: 'boolean',
  //   defaultValue: false,
  //   requiresReload: true,
  //   integration: {
  //     status: 'integration-point',
  //     reason: 'Extension host adapters can read this setting to enable extra debug logging.',
  //   },
  // },
  // {
  //   id: 'workbench.capture.defaultLane',
  //   label: 'Default Capture Lane',
  //   description: 'Preferred lane for new captures when capture integrations are available.',
  //   category: 'Capture',
  //   type: 'string',
  //   defaultValue: 'inbox',
  //   render: { placeholder: 'inbox' },
  //   integration: {
  //     status: 'integration-point',
  //     reason:
  //       'Capture extensions can read this setting from runtime.settings when choosing a default destination.',
  //   },
  // },
  // {
  //   id: 'workbench.capture.autoVersion',
  //   label: 'Auto Version Captures',
  //   description: 'Creates a new version when a matching capture already exists.',
  //   category: 'Capture',
  //   type: 'boolean',
  //   defaultValue: true,
  //   integration: {
  //     status: 'integration-point',
  //     reason: 'Capture extensions can read this setting before creating a new capture or version.',
  //   },
  // },
  // {
  //   id: 'workbench.capture.highlightExistingCaptures',
  //   label: 'Highlight Existing Captures',
  //   description: 'Highlights already captured selections when capture surfaces support it.',
  //   category: 'Capture',
  //   type: 'boolean',
  //   defaultValue: true,
  //   integration: {
  //     status: 'integration-point',
  //     reason: 'Capture surfaces can read this setting before decorating existing captures.',
  //   },
  // },
  // {
  //   id: 'workbench.storage.provider',
  //   label: 'Storage Provider',
  //   description: 'Preferred Workbench storage backend.',
  //   category: 'Storage',
  //   type: 'enum',
  //   defaultValue: 'host',
  //   options: [
  //     { label: 'Host Default', value: 'host' },
  //     { label: 'Local Browser', value: 'local' },
  //     { label: 'Remote Sync', value: 'remote' },
  //   ],
  //   requiresReload: true,
  //   integration: {
  //     status: 'integration-point',
  //     reason:
  //       'Host adapters own storage backends; this setting records the preferred provider for hosts that support selection.',
  //   },
  // },
  // {
  //   id: 'workbench.sync.enabled',
  //   label: 'Settings Sync',
  //   description: 'Keeps user settings synchronized when a sync provider is connected.',
  //   category: 'Sync',
  //   type: 'boolean',
  //   defaultValue: false,
  //   integration: {
  //     status: 'integration-point',
  //     reason: 'Sync providers can read this setting before syncing persisted Workbench settings.',
  //   },
  // },
  // {
  //   id: 'workbench.publishing.defaultVisibility',
  //   label: 'Default Publishing Visibility',
  //   description: 'Default visibility for publish-capable workflows.',
  //   category: 'Publishing',
  //   type: 'enum',
  //   defaultValue: 'private',
  //   options: [
  //     { label: 'Private', value: 'private' },
  //     { label: 'Workspace', value: 'workspace' },
  //     { label: 'Public', value: 'public' },
  //   ],
  //   integration: {
  //     status: 'integration-point',
  //     reason: 'Publishing extensions can read this setting for their default visibility.',
  //   },
  // },
  // {
  //   id: 'workbench.experimental.commandCenter',
  //   label: 'Command Center',
  //   description: 'Enables experimental command center affordances.',
  //   category: 'Experimental',
  //   type: 'boolean',
  //   defaultValue: false,
  //   experimental: true,
  // },
  // {
  //   id: 'launcher.showRecentApps',
  //   label: 'Show Recent Apps',
  //   description: 'Shows recently launched apps in the Workbench launcher.',
  //   category: 'Launcher',
  //   type: 'boolean',
  //   defaultValue: true,
  //   tags: ['apps', 'recent'],
  // },
  // {
  //   id: 'launcher.showPinnedApps',
  //   label: 'Show Pinned Apps',
  //   description: 'Shows pinned apps in the Workbench launcher.',
  //   category: 'Launcher',
  //   type: 'boolean',
  //   defaultValue: true,
  //   tags: ['apps', 'pinned'],
  // },
  // {
  //   id: 'launcher.showCategories',
  //   label: 'Show Categories',
  //   description: 'Shows app category chips in the Workbench launcher.',
  //   category: 'Launcher',
  //   type: 'boolean',
  //   defaultValue: true,
  //   tags: ['apps', 'categories'],
  // },
  // {
  //   id: 'launcher.defaultView',
  //   label: 'Default View',
  //   description: 'Controls the default app layout in the Workbench launcher.',
  //   category: 'Launcher',
  //   type: 'enum',
  //   defaultValue: 'grid',
  //   options: [
  //     { label: 'Grid', value: 'grid' },
  //     { label: 'List', value: 'list' },
  //   ],
  //   tags: ['apps', 'layout'],
  // },
  // {
  //   id: 'launcher.enableWorkspaceSwitcher',
  //   label: 'Workspace Switcher',
  //   description: 'Shows workspace switching controls in the Workbench launcher.',
  //   category: 'Launcher',
  //   type: 'boolean',
  //   defaultValue: true,
  //   tags: ['workspace', 'desktop'],
  // },
  {
    id: 'workbench.servers.defaultStartup',
    label: 'Default Server Startup',
    description: 'Fallback startup mode for server extensions that do not declare one.',
    category: 'Servers',
    type: 'enum',
    defaultValue: 'manual',
    options: [
      { label: 'Auto', value: 'auto' },
      { label: 'Manual', value: 'manual' },
      { label: 'Disabled', value: 'disabled' },
    ],
    tags: ['server', 'runtime', 'extensions'],
  },
  {
    id: 'workbench.servers.defaultRestartPolicy',
    label: 'Default Restart Policy',
    description: 'Fallback restart behavior for managed server extensions.',
    category: 'Servers',
    type: 'enum',
    defaultValue: 'on-failure',
    options: [
      { label: 'Never', value: 'never' },
      { label: 'On Failure', value: 'on-failure' },
      { label: 'Always', value: 'always' },
    ],
    tags: ['server', 'runtime', 'restart'],
  },
  {
    id: 'workbench.servers.healthIntervalMs',
    label: 'Health Check Interval',
    description: 'Default server health check interval in milliseconds.',
    category: 'Servers',
    type: 'number',
    defaultValue: 5000,
    render: { min: 1000, max: 60000, step: 500 },
    tags: ['server', 'health'],
  },
  {
    id: 'workbench.servers.logBufferSize',
    label: 'Log Buffer Size',
    description: 'Maximum in-memory log entries retained per server.',
    category: 'Servers',
    type: 'number',
    defaultValue: 500,
    render: { min: 100, max: 10000, step: 100 },
    tags: ['server', 'logs'],
  },
]
