package seed

import (
	"context"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/activelane/activelane/go/alx"
	"github.com/activelane/activelane/go/registry"
	"github.com/activelane/activelane/go/registryconfig"
)

func TestFullPipelineIdempotencySearchAndClean(t *testing.T) {
	registryRoot := t.TempDir()
	config := registryconfig.Config{Version: 1, Registries: []registryconfig.Registry{{ID: "local", Type: "directory", Path: registryRoot, Enabled: true, Scopes: []string{"local"}}}}
	config.Registries[0].Scopes = append(config.Registries[0].Scopes, Publishers(42)...)
	options := Options{RegistryID: "local", Count: 8, Seed: 42, Profile: MarketplaceDemo}
	first, err := Run(context.Background(), config, options)
	if err != nil {
		t.Fatal(err)
	}
	if first.Published != 8 || first.Existing != 0 {
		t.Fatalf("unexpected first result: %+v", first)
	}
	second, err := Run(context.Background(), config, options)
	if err != nil {
		t.Fatal(err)
	}
	if second.Published != 0 || second.Existing != 8 {
		t.Fatalf("repeat was not idempotent: %+v", second)
	}
	store, err := registry.NewStore(registryRoot)
	if err != nil {
		t.Fatal(err)
	}
	// Publish a normal package outside the seeder; cleanup must leave it untouched.
	genuineDir := filepath.Join(t.TempDir(), "genuine")
	if err := os.MkdirAll(filepath.Join(genuineDir, "extension"), 0755); err != nil {
		t.Fatal(err)
	}
	genuine := alx.Manifest{SchemaVersion: alx.ManifestSchemaVersion, ID: "@local/genuine", Publisher: "local", Name: "genuine", DisplayName: "Genuine", Version: "1.0.0", Description: "Not generated by the seeder.", Entry: "extension/main.js", Engines: map[string]string{"activelane": "*"}, HostSupport: []string{"desktop"}, ExtensionKind: []string{"workbench"}, Visibility: "public"}
	data, _ := json.Marshal(genuine)
	if err := os.WriteFile(filepath.Join(genuineDir, alx.ManifestFile), data, 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(genuineDir, "extension/main.js"), []byte("export default { manifest: { id: '@local/genuine', version: '1.0.0' } }\n"), 0644); err != nil {
		t.Fatal(err)
	}
	pkg := filepath.Join(t.TempDir(), "genuine.alx")
	if _, err := alx.PackDir(genuineDir, pkg); err != nil {
		t.Fatal(err)
	}
	file, err := os.Open(pkg)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = store.Publish(context.Background(), "local", "genuine", file); err != nil {
		t.Fatal(err)
	}
	file.Close()
	items, err := store.List("")
	if err != nil {
		t.Fatal(err)
	}
	if len(items) != 9 {
		t.Fatalf("search returned %d items", len(items))
	}
	removed, err := Clean(config, "local")
	if err != nil {
		t.Fatal(err)
	}
	if removed != 8 {
		t.Fatalf("removed %d", removed)
	}
	items, err = store.List("")
	if err != nil {
		t.Fatal(err)
	}
	if len(items) != 1 {
		t.Fatalf("expected only genuine record, got: %d", len(items))
	}
	_, err = store.GetExtension("local", "genuine")
	if errors.Is(err, registry.ErrNotFound) || err != nil {
		t.Fatalf("genuine extension was removed: %v", err)
	}
}
