// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class FileHandle {
    "name": string;
    "path"?: string;
    "contents"?: string;

    /** Creates a new FileHandle instance. */
    constructor($$source: Partial<FileHandle> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileHandle instance from a string or object.
     */
    static createFrom($$source: any = {}): FileHandle {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileHandle($$parsedSource as Partial<FileHandle>);
    }
}

export class FileSystemEntry {
    "name": string;
    "path": string;
    "uri": string;
    "type": string;
    "size"?: number;
    "modifiedAt"?: string;
    "hidden"?: boolean;

    /** Creates a new FileSystemEntry instance. */
    constructor($$source: Partial<FileSystemEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileSystemEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FileSystemEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileSystemEntry($$parsedSource as Partial<FileSystemEntry>);
    }
}
