import type { App, Plugin as VuePlugin } from 'vue'
import { installComponents } from './component-registry'
import './styles/index.css'

// TODO remove
export { default as AlCommandActionRow } from './components/command/CommandActionRow.vue'
export { default as AlCommandBar } from './components/command/CommandBar.vue'
export { default as AlCommandDialog } from './components/command/CommandDialog.vue'
export { default as AlCommandSurface } from './components/command/CommandSurface.vue'
export { default as AlDashboardActionBar } from './components/dashboard/DashboardActionBar.vue'
export { default as AlDashboardActivityFeed } from './components/dashboard/DashboardActivityFeed.vue'
export { default as AlDashboardAttentionPanel } from './components/dashboard/DashboardAttentionPanel.vue'
export { default as AlDashboardContent } from './components/dashboard/DashboardContent.vue'
export { default as AlDashboardMain } from './components/dashboard/DashboardMain.vue'
export { default as AlDashboardNotice } from './components/dashboard/DashboardNotice.vue'
export { default as AlDashboardPageContainer } from './components/dashboard/DashboardPageContainer.vue'
export { default as AlDashboardPageHeader } from './components/dashboard/DashboardPageHeader.vue'
export { default as AlDashboardQuickActions } from './components/dashboard/DashboardQuickActions.vue'
export { default as AlDashboardSection } from './components/dashboard/DashboardSection.vue'
export { default as AlDashboardSidebar } from './components/dashboard/DashboardSidebar.vue'
export { default as AlDashboardSidebarItem } from './components/dashboard/DashboardSidebarItem.vue'
export { default as AlDashboardSplit } from './components/dashboard/DashboardSplit.vue'
export { default as AlDashboardStatGrid } from './components/dashboard/DashboardStatGrid.vue'
export { default as AlDashboardTopbar } from './components/dashboard/DashboardTopbar.vue'
export { default as AlDashboardWidget } from './components/dashboard/DashboardWidget.vue'
export type { DashboardActionItem } from './components/dashboard/types'
export { default as AlActionRow } from './components/data-display/ActionRow.vue'
export { default as AlCodeBlock } from './components/data-display/CodeBlock.vue'
export { default as AlEmptyState } from './components/data-display/EmptyState.vue'
export { default as AlKeyValueList } from './components/data-display/KeyValueList.vue'
export { default as AlKeyValueRow } from './components/data-display/KeyValueRow.vue'
export { default as AlListGroup } from './components/data-display/ListGroup.vue'
export { default as AlLoadingState } from './components/data-display/LoadingState.vue'
export { default as AlMetadataChips } from './components/data-display/MetadataChips.vue'
export { default as AlMetadataList } from './components/data-display/MetadataList.vue'
export { default as AlMetricCard } from './components/data-display/MetricCard.vue'
export { default as AlPreviewCard } from './components/data-display/PreviewCard.vue'
export { default as AlSelectableItem } from './components/data-display/SelectableItem.vue'
export { default as AlStatBlock } from './components/data-display/StatBlock.vue'
export { default as AlSurfaceFrame } from './components/data-display/SurfaceFrame.vue'
export { default as AlTable } from './components/data-display/Table.vue'
export { default as AlTimeline } from './components/data-display/Timeline.vue'
export { default as AlAlert } from './components/feedback/Alert.vue'
export { default as AlProgressBar } from './components/feedback/ProgressBar.vue'
export { default as AlSpinner } from './components/feedback/Spinner.vue'
export { default as AlStatusBanner } from './components/feedback/StatusBanner.vue'
export { default as AlToastViewport } from './components/feedback/ToastViewport.vue'
export { default as AlAIChatTextbox } from './components/forms/AIChatTextbox.vue'
export { default as AlCombobox } from './components/forms/Combobox.vue'
export { default as AlDatePicker } from './components/forms/DatePicker.vue'
export { default as AlField } from './components/forms/Field.vue'
export { default as AlInlineFormRow } from './components/forms/InlineFormRow.vue'
export { default as AlMultiSelect } from './components/forms/MultiSelect.vue'
export { default as AlSearchBar } from './components/forms/SearchBar.vue'
export { default as AlSearchInput } from './components/forms/SearchInput.vue'
export { default as AlSettingsPanel } from './components/forms/SettingsPanel.vue'
export { default as AlSettingsRow } from './components/forms/SettingsRow.vue'
export { default as AlAppShell } from './components/layout/AppShell.vue'
export { default as AlContentSurface } from './components/layout/ContentSurface.vue'
export { default as AlDetailPane } from './components/layout/DetailPane.vue'
export { default as AlDetailPanel } from './components/layout/DetailPanel.vue'
export { default as AlFilterBar } from './components/layout/FilterBar.vue'
export { default as AlHeaderBar } from './components/layout/HeaderBar.vue'
export { default as AlInlineGroup } from './components/layout/InlineGroup.vue'
export { default as AlInspectorPanel } from './components/layout/InspectorPanel.vue'
export { default as AlListPane } from './components/layout/ListPane.vue'
export { default as AlMasterDetail } from './components/layout/MasterDetail.vue'
export { default as AlPage } from './components/layout/Page.vue'
export { default as AlPanel } from './components/layout/Panel.vue'
export { default as AlPanelHeader } from './components/layout/PanelHeader.vue'
export { default as AlResizeHandle } from './components/layout/ResizeHandle.vue'
export { default as AlResponsiveActions } from './components/layout/ResponsiveActions.vue'
export { default as AlSection } from './components/layout/Section.vue'
export { default as AlSectionHeader } from './components/layout/SectionHeader.vue'
export { default as AlShell } from './components/layout/Shell.vue'
export { default as AlSidebarSection } from './components/layout/SidebarSection.vue'
export { default as AlSplitPane } from './components/layout/SplitPane.vue'
export { default as AlStack } from './components/layout/Stack.vue'
export { default as AlStatusBar } from './components/layout/StatusBar.vue'
export { default as AlTabbedWorkspace } from './components/layout/TabbedWorkspace.vue'
export { default as AlToolbar } from './components/layout/Toolbar.vue'
export { default as AlTopBar } from './components/layout/TopBar.vue'
export { default as AlWorkspaceShell } from './components/layout/WorkspaceShell.vue'
export { default as AlBreadcrumb } from './components/navigation/Breadcrumb.vue'
export { default as AlBreadcrumbs } from './components/navigation/Breadcrumbs.vue'
export { default as AlNavItem } from './components/navigation/NavItem.vue'
export { default as AlPagination } from './components/navigation/Pagination.vue'
export { default as AlSidebar } from './components/navigation/Sidebar.vue'
export { default as AlSidebarRail } from './components/navigation/SidebarRail.vue'
export { default as AlViewSwitcher } from './components/navigation/ViewSwitcher.vue'
export { default as AlAlertDialog } from './components/overlays/AlertDialog.vue'
export { default as AlContextMenu } from './components/overlays/ContextMenu.vue'
export { default as AlDialog } from './components/overlays/Dialog.vue'
export { default as AlDrawer } from './components/overlays/Drawer.vue'
export { default as AlDropdown } from './components/overlays/Dropdown.vue'
export { default as AlDropdownMenu } from './components/overlays/DropdownMenu.vue'
export { default as AlHoverCard } from './components/overlays/HoverCard.vue'
export { default as AlMenubar } from './components/overlays/Menubar.vue'
export { default as AlModal } from './components/overlays/Modal.vue'
export { default as AlPopover } from './components/overlays/Popover.vue'
export { default as AlScrollArea } from './components/overlays/ScrollArea.vue'
export { default as AlSheet } from './components/overlays/Sheet.vue'
export { default as AlTooltip } from './components/overlays/Tooltip.vue'
export { default as AlCaptureListItem } from './components/sidepanel/CaptureListItem.vue'
export { default as AlContentPreviewBlock } from './components/sidepanel/ContentPreviewBlock.vue'
export { default as AlMetadataRow } from './components/sidepanel/MetadataRow.vue'
export { default as AlSidepanelShell } from './components/sidepanel/SidepanelShell.vue'
export { default as AlStickyPanelHeader } from './components/sidepanel/StickyPanelHeader.vue'
export { default as AlTreeItem } from './components/sidepanel/TreeItem.vue'
export { default as AlThemeModeSelector } from './components/theme/ThemeModeSelector.vue'
export { default as AlThemeToggle } from './components/theme/ThemeToggle.vue'
// TODO remove

export { default as AlAccordion } from './components/ui/Accordion.vue'
export { default as AlAvatar } from './components/ui/Avatar.vue'
export * from './components/ui/accordion'
export * from './components/ui/alert'
export * from './components/ui/alert-dialog'
export * from './components/ui/aspect-ratio'
export * from './components/ui/avatar'
export { default as AlBadge } from './components/ui/Badge.vue'
export { default as AlButton } from './components/ui/Button.vue'
export * from './components/ui/badge'
export * from './components/ui/breadcrumb'
export * from './components/ui/button'
export * from './components/ui/button-group'
export { default as AlCard } from './components/ui/Card.vue'
export { default as AlCheckbox } from './components/ui/Checkbox.vue'
export { default as AlCollapsible } from './components/ui/Collapsible.vue'
export * from './components/ui/calendar'
export * from './components/ui/card'
export * from './components/ui/carousel'
export * from './components/ui/chart'
export * from './components/ui/checkbox'
export * from './components/ui/collapsible'
export * from './components/ui/combobox'
export {
  Command as UiCommand,
  CommandDialog as UiCommandDialog,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandSeparator,
  CommandShortcut,
  provideCommandContext,
  provideCommandGroupContext,
  useCommand,
  useCommandGroup,
} from './components/ui/command'
export * from './components/ui/context-menu'
export * from './components/ui/date-picker'
export * from './components/ui/dialog'
export * from './components/ui/drawer'
export * from './components/ui/dropdown-menu'
export * from './components/ui/empty'
export * from './components/ui/field'
export * from './components/ui/form'
export * from './components/ui/hover-card'
export { default as AlIconButton } from './components/ui/IconButton.vue'
export { default as AlInput } from './components/ui/Input.vue'
export * from './components/ui/input'
export * from './components/ui/input-group'
export * from './components/ui/input-otp'
export * from './components/ui/item'
export { default as AlKbd } from './components/ui/Kbd.vue'
export * from './components/ui/kbd'
export { default as AlLabel } from './components/ui/Label.vue'
export * from './components/ui/label'
export * from './components/ui/menubar'
export * from './components/ui/native-select'
export * from './components/ui/navigation-menu'
export * from './components/ui/number-field'
export { default as AlProgress } from './components/ui/Progress.vue'
export * from './components/ui/pagination'
export * from './components/ui/pin-input'
export * from './components/ui/popover'
export * from './components/ui/progress'
export { default as AlRadioGroup } from './components/ui/RadioGroup.vue'
export * from './components/ui/radio-group'
export * from './components/ui/range-calendar'
export * from './components/ui/resizable'
export { default as AlSelect } from './components/ui/Select.vue'
export { default as AlSeparator } from './components/ui/Separator.vue'
export { default as AlSkeleton } from './components/ui/Skeleton.vue'
export { default as AlSwitch } from './components/ui/Switch.vue'
export * from './components/ui/scroll-area'
export * from './components/ui/select'
export * from './components/ui/separator'
export * from './components/ui/sheet'
export * from './components/ui/sidebar'
export * from './components/ui/skeleton'
export * from './components/ui/slider'
export * from './components/ui/sonner'
export * from './components/ui/spinner'
export * from './components/ui/stepper'
export * from './components/ui/switch'
export { default as AlTabs } from './components/ui/Tabs.vue'
export { default as AlTextarea } from './components/ui/Textarea.vue'
export * from './components/ui/table'
export * from './components/ui/tabs'
export * from './components/ui/tags-input'
export * from './components/ui/textarea'
export * from './components/ui/toast'
export * from './components/ui/toggle'
export * from './components/ui/toggle-group'
export * from './components/ui/tooltip'
export * from './components/ui/typography'
export { useRovingSelection } from './composables/useRovingSelection'
export {
  activeLaneThemeNames,
  initializeTheme,
  THEME_MODES,
  THEME_STORAGE_KEY,
  useTheme,
} from './composables/useTheme'
export { useToast } from './composables/useToast'
export { cn, createId } from './lib/utils'
export { badgeVariants, buttonVariants } from './lib/variants'
export type { DesignSystemRegistry } from './registry'
export { createDesignSystemRegistry } from './registry'
export type { DensityMode, ThemeMode } from './tokens'
export { densityModes, motion, themeModes, zIndex } from './tokens'
export type {
  CommandAction,
  ComponentSize,
  Density,
  Intent,
  NavigationItem,
  ResolvedTheme,
  SelectOption,
  SidebarNavGroup,
  SidebarNavItem,
  Tone,
} from './types'

export const ActiveLaneShadcnPlugin: VuePlugin = {
  install(app: App) {
    installComponents.forEach(([name, component]) => {
      app.component(name, component)
    })
  },
}
